default_platform(:android)

platform :android do

  desc "Build APK et envoyer sur Firebase"
  lane :distribute do

    # ── Build debug APK
    gradle(
      task: "assembleDebug",
      project_dir: "./android",
      print_command: true
    )

    # ── Chemin exact de l'APK généré
    apk_path = "./android/app/build/outputs/apk/debug/app-debug.apk"

    # ── Upload sur Firebase App Distribution avec token
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],          # Firebase App ID (depuis GitHub Secrets)
      testers: ENV["FIREBASE_TESTERS"],     # Emails des testeurs séparés par des virgules
      token: ENV["FIREBASE_TOKEN"],         # <- correct
      release_notes: "Nouvelle version automatique",
      apk_path: apk_path,
      upload_timeout: 1200, # 20 minutes
      debug: true           # Affiche tous les logs d'upload
    )

  end

end