platform :android do

  desc "Build APK et envoyer sur Firebase"
  lane :distribute do

    # Build debug APK
    gradle(
      task: "assembleDebug",
      project_dir: "./android",
      print_command: true
    )

    # Chemin exact de l'APK généré
    apk_path = "./android/app/build/outputs/apk/debug/app-debug.apk"

    # Upload sur Firebase App Distribution
    firebase_app_distribution(
      app: "1:205993429155:android:2fd61cebc9ef91cb0f5716",
      testers: "kakpopascl610@gmail.com",
      release_notes: "Nouvelle version automatique",
      apk_path: apk_path,
      upload_timeout: 1200, # 20 minutes
      debug: true           # pour voir tous les logs d'upload
    )

  end

end